spring:
  application:
    name: lm-projects
  datasource:
    url: jdbc:postgresql://localhost:5432/lamuralla
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
server:
  port: '8082'
app:
  cors:
    allowed-origins: http://localhost:3000
  jwt:
    secret: ${JWT_SECRET}
auth:
  service:
    url: http://localhost:8081/api/oauth
issues:
  service:
    url: http://localhost:8080/api/issues
config:
  service:
    url: http://localhost:8088/api/config