spring:
  application:
    name: lm-projects
  datasource:
    url: jdbc:postgresql://localhost:5433/lamuralla
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
app:
  cors:
    allowed-origins: https://cartagenacorporation.com,https://www.cartagenacorporation.com
  jwt:
    secret: ${JWT_SECRET}
auth:
  service:
    url: http://localhost:8081/api/oauth
issues:
  service:
    url: http://localhost:8090/api/issues
